### Test GET /words (requires valid JWT Bearer token)

@baseUrl = http://localhost:8080
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjZlODk1YzQ3YTA0YzVmNmRlMzExMmFmZjE2ODFhMzUwNzdkMWNjZDQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vd29ydC1zY2hhdHotZjYwZDAiLCJhdWQiOiJ3b3J0LXNjaGF0ei1mNjBkMCIsImF1dGhfdGltZSI6MTc0ODg5MTk5NiwidXNlcl9pZCI6IkxYdXdXQ2E3ZnFYUmJ4Wm9NMExJQXNDMTJXYjIiLCJzdWIiOiJMWHV3V0NhN2ZxWFJieFpvTTBMSUFzQzEyV2IyIiwiaWF0IjoxNzQ4ODkxOTk2LCJleHAiOjE3NDg4OTU1OTYsImVtYWlsIjoidHN5YnVsaXZza3lpQGxpdmUuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRzeWJ1bGl2c2t5aUBsaXZlLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.YyiZT2SVdOMEM7ehmiS-rljxo1J3FFlN9Yo8mEruSVWTdXDY80kfsFUWwxv6doc-9gfWeKeoHW20IxNhDkYDZVkO6h8Qs23Gv2B4CQz93fXuoH7bi5v2nuVvwRMmvsm3KumLRF5KGI8Tdb_QX_8D0RP7jGhzWb_GN9e04G8P1eB-BRohaTEYOACTVP588o8iuSHgd30NN7BAwDMUGcEl7I4X5oNQdh4hZxPLYT6AE5YDGEk6FLBdcsLdksgKdKmdCFAAYoKbASmiCCiEQNIcLVWrsGT9yef-suuFIvNSjzdh-rK1ugBrgzPMJu9WgpAteiVqDJzsTC-nEq8XEYIomg

GET {{baseUrl}}/words
Authorization: Bearer {{token}}
Accept: application/json
